### ISSUE TITLE
add_spl_patients: swapped saved file names?

### ISSUE THREAD

**Issue by chopardda** [mims-harvard/SHEPHERD#5]
Hello, 

I am currently in the process of trying to evaluate the pre-trained SHEPHERD model for causal gene discovery on the myGene2 dataset. However, after computing the SPL matrix for this particular dataset using the `add_spl_to_patients.py` script, I encounter an issue. It seems that when I subsequently run the `train.py` script (with the flag `--do_inference` for evaluation), an error occurs. Interestingly, I have discovered that this error can be resolved by swapping the names of the saved files, namely `spl_index_fname` and `spl_matrix_fname` as follows: 

```
with open(str(project_config.PROJECT_DIR / 'patients' / spl_index_fname), 'wb') as handle:
        pickle.dump(spl_indexing, handle, protocol=pickle.HIGHEST_PROTOCOL)
np.save(str(project_config.PROJECT_DIR / 'patients' / spl_matrix_fname), patients_spl_matrix)
```

Is there a specific reason for this behavior? I'm wondering if there is something I might be doing incorrectly.

**Comment by michellemli** [comment]
Hello! Thank you for bringing this to our attention! We thought we'd pushed this change, but in fact it was not. We've fixed this issue in our newest commit.
